# Generated by Django 3.1.2 on 2021-01-04 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_num', models.IntegerField(max_length=15)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeemng.empcategory')),
            ],
        ),
    ]
